name: Library builds (csharp)

on:
  push:
    branches: [ 'master', 'main', 'develop', 'actions_shared', 'v*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'master', 'main', 'develop' ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [self-hosted]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Display system info
      run: uname -a

    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'

    #- name: Install Python dependencies
     # run: python -m pip install requests packaging six

    - name: Extract CoolProp version from CMakeLists.txt
      shell: bash
      run: |
        set -x
        COOLPROP_VERSION=$(python dev/extract_version.py --cmake-only)
        echo COOLPROP_VERSION=$COOLPROP_VERSION >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B build -S . -DCOOLPROP_CSHARP_MODULE=ON -DCOOLPROP_NO_EXAMPLES=ON -DCMAKE_BUILD_TYPE:STRING=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build build --target install -j $(nproc) --config ${{ env.BUILD_TYPE }}

   
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
          name: csharp-${{ matrix.os }}
          path: install_root
